/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'btu' at '3/16/16 7:29 PM' with Gradle 2.5
 *
 * @author btu, @date 3/16/16 7:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
